name: 'otel-action'
description: 'Generates and exports OpenTelemetry spans from GitHub workflow runs'
author: 'EricStG'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'microscope'
  color: 'grey'

# Define your inputs here.
inputs:
  attempt:
    description: 'The attempt number of the run'
    required: true
  owner:
    description: 'The owner of the repository where the workflow ran'
    required: true
  repo:
    description: 'The repository where the workflow ran'
    required: true
  runId:
    description: 'The ID of the run to export'
    required: true
  token:
    description: 'The GitHub token to access the run information'
    required: true

outputs:

runs:
  using: node20
  main: dist/index.js
