receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:

  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_APIKEY}"
      "x-honeycomb-dataset": "otel-action-test-collector"

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
