name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Start containers
        id: docker-start
        run: |
         docker compose -f docker-compose.yml pull --quiet
         docker compose -f docker-compose.yml up -d --quiet-pull
         .github/workflows/wait_for_http_200.sh http://localhost:13133
        
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          attempt: 1
          owner: EricStG
          repo: otel-action
          runId: 7374922069
          token: ${{ secrets.GITHUB_TOKEN }}
